Update detox types to avoid global conflicts
When running tsc -p ., because "expect" is already declared (by Jest for instance), checking types will fail

```
$ tsc -p .
node_modules/@types/detox/index.d.ts:15:11 - error TS2451: Cannot redeclare block-scoped variable 'expect'.

15     const expect: Detox.Expect<Detox.Expect<Promise<void>>>;
             ~~~~~~

  node_modules/@types/jest/index.d.ts:47:15
    47 declare const expect: jest.Expect;
                     ~~~~~~
    'expect' was also declared here.

node_modules/@types/jest/index.d.ts:47:15 - error TS2451: Cannot redeclare block-scoped variable 'expect'.

47 declare const expect: jest.Expect;
                 ~~~~~~

  node_modules/@types/detox/index.d.ts:15:11
    15     const expect: Detox.Expect<Detox.Expect<Promise<void>>>;
                 ~~~~~~
    'expect' was also declared here.


Found 2 errors.
```